apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: productpage-v1
spec:
  scaleTargetRef:
    kind: Deployment
    name: productpage-v1
  minReplicaCount: 1
  maxReplicaCount: 100
  cooldownPeriod: 5
  pollingInterval: 1
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 120
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "35"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ratings-v1
spec:
  scaleTargetRef:
    kind: Deployment
    name: ratings-v1
  minReplicaCount: 1
  maxReplicaCount: 100
  cooldownPeriod: 5
  pollingInterval: 1
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 120
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "35"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: reviews-v1
spec:
  scaleTargetRef:
    kind: Deployment
    name: reviews-v1
  minReplicaCount: 1
  maxReplicaCount: 100
  cooldownPeriod: 5
  pollingInterval: 1
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 120
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "35"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: reviews-v2
spec:
  scaleTargetRef:
    kind: Deployment
    name: reviews-v2
  minReplicaCount: 1
  maxReplicaCount: 100
  cooldownPeriod: 5
  pollingInterval: 1
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 120
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "35"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: reviews-v3
spec:
  scaleTargetRef:
    kind: Deployment
    name: reviews-v3
  minReplicaCount: 1
  maxReplicaCount: 100
  cooldownPeriod: 5
  pollingInterval: 1
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 120
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "35"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: details-v1
spec:
  scaleTargetRef:
    kind: Deployment
    name: details-v1
  minReplicaCount: 1
  maxReplicaCount: 100
  cooldownPeriod: 5
  pollingInterval: 1
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 120
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "35"
---

