apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlautoscaler
  labels:
    apps: rlautoscaler
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rlautoscaler
      version: v1
  template:
    metadata:
      labels:
        app: rlautoscaler
        version: v1
    spec:
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: config-override
      containers:
        - name: autoscaler
          image: aveshasystems/smart-scaler:v0.6.1 # Change this to match the local repo, remove imagePullSecrets below (line 45) if not needed 
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            [
              "wandb disabled & python policy/inference_script.py -c /data/pse_results/bookinfo-data/bookinfo-app_mesh_smart_scaler_config.json --no-smartscalerdb --mode mesh --restore -p /home/avesha/rl/rlautoscaler/checkpoint_010430 --inference-session bookinfo-high-traffic",
            ]
          # args: ["sleep infinity"]
          resources:
            requests:
              memory: 2Gi
              cpu: 1
          volumeMounts:
            - name: config-volume
              mountPath: /data/config
          ports:
            - containerPort: 9900
            - containerPort: 8265
      imagePullSecrets: # Remove this if secret is not needed to pull the repo
        - name: avesha-docker
      #terminationGracePeriodSeconds: 30
      # nodeSelector:
      #   avesha/node-type: "rlautoscaler"
      # tolerations:
      # - key: "non-app-pods-no-schedule"
      #   value: "true"
      #   effect: "NoSchedule"
