{
 "title": "SmartScaler",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AppNamespace", "query": "demo" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$AppNamespace\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pod Service Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(istio_requests_total{destination_workload=~\"$pod.*\", reporter=\"destination\"}[1m])))",
     "legendFormat": "Total  Traffic"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_workload=~\"$pod.*\", reporter=\"destination\", response_code!~\"200|3.+\"}[1m]))  ",
     "legendFormat": "Error Traffic"
    },
    {
     "expr": "hpa_num_pods{job=\"$pod\",  kubernetes_pod_name=\"$pod\"}\r\n",
     "legendFormat": "Num Pods by SmartScaler"
    },
    {
     "expr": "(sum(kube_pod_status_ready{pod=~\"$pod.+\"})) ",
     "legendFormat": "Pods Ready"
    },
    {
     "expr": "predicted_rps{job=\"$pod\"} offset -1m",
     "legendFormat": "Predicted RPS"
    },
    {
     "expr": "(sum(kube_pod_status_scheduled{pod=~\"$pod.+\"})) ",
     "legendFormat": "Pods Scheduled"
    }
   ]
  },
  {
   "title": "$pod: Aggregate Pod Minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(kube_pod_status_ready{pod=~\"$pod.+\"}[$__range]) )/4",
     "legendFormat": "$pod: Aggregate Pod Minutes"
    }
   ]
  },
  {
   "title": "$pod Percentage Response less than 500 ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~\"$pod.*\",le=\"500\"}[120s])) /sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~\"$pod.*\",le=\"+Inf\"}[120s])))*100",
     "legendFormat": "% Response < 500 ms"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(increase(istio_requests_total{namespace=\"$AppNamespace\", reporter=\"destination\", response_code!~\"200|3.+\",destination_workload=~\"$pod.*\"}[$__range])) by ( destination_app) / sum(increase(istio_requests_total{namespace=\"$AppNamespace\", reporter=\"destination\",destination_workload=~\"$pod.*\"\r\n}[$__range])) by ( destination_app))*100"
    }
   ]
  },
  {
   "title": "Pod CPU Utilisation %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "((sum(rate(container_cpu_usage_seconds_total{container=~\".*[A-Za-z0-9].*|!POD\",pod=~\"$pod.*\"}[120s])))/ sum(kube_pod_container_resource_requests{container=~\".*[A-Za-z0-9].*|!POD\",pod=~\"$pod.*\", resource=\"cpu\"}))",
     "legendFormat": "$pod cpu utilization %"
    }
   ]
  },
  {
   "title": "$pod: Pod CPU Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{container=~\".*[A-Za-z0-9].*|!POD\",pod=~\"$pod.*\",resource=\"cpu\"})/(sum(kube_pod_status_ready{pod=~\"$pod.+\"}))",
     "legendFormat": "$pod: Aggregate Pod Minutes"
    }
   ]
  }
 ]
}